#!/usr/bin/env bash
# This is a script that transfers a file from our client to the server

# Check if number of arguments is equal to 4
if [ $# -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# -o StrictHostKeyChecking=no disables strict host key checking
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/