#!/usr/bin/env bash
# This is a script that transfers a file from our client to the server
# Requirements:
# - Accepts 4 parameters
#    1. The path to the file to be transferred
#    2. The IP of the server we want to transfer the file to
#    3. The username scp connects with
#    4. The path to the SSH private key that scp uses
# - Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
# - scp must transfer the file to the user home directory ~/
# - Strict host key checking must be disabled when using scp

# Check if number of arguments is equal to 4
if [ $# -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# -o StrictHostKeyChecking=no disables strict host key checking
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/