#!/usr/bin/env bash
# This script configures a new Ubuntu machine with nginx
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo /etc/init.d/nginx restart