#!/usr/bin/env bash
# This script configures a new Ubuntu machine to redirect /redirect_me to another page

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx
echo "Hello World!" > /var/www/html/index.html

# Configure the redirection
sed -i '/listen 80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
