#!/usr/bin/env bash
# This script configures a new Ubuntu machine to redirect /redirect_me to another page

# Install nginx
apt-get update -y
apt-get install nginx -y

# Create initial index.html file
echo 'Hello World!' > /var/www/html/index.html

# Configure the redirection
sed -i '/listen 80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Create the 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure the 404 error page
sed -i 's/listen 80 default_server;/listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\tinternal;\n\t}/' /etc/nginx/sites-enabled/default

# Restart nginx
service nginx restart
