#!/usr/bin/env bash
# This is a script that:
#   Starts a process in /tmp/my_process
#   Creates a file containing its PID in /var/run/my_process.pid
#   Displays manage_my_process started
#   Stops the process when receiving a SIGTERM signal
#   Deletes the file /var/run/my_process.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

if [ $# -gt 0 ]
then
    if [ "$1" == "start" ]
    then
        ./manage_my_process &
        touch /var/run/my_process.pid
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
    elif [ "$1" == "stop" ]
    then
        echo "manage_my_process stopped"
        kill "$(cat /var/run/my_process.pid)"
        rm -f /var/run/my_process.pid
    elif [ "$1" == "restart" ]
    then
        kill "$(cat /var/run/my_process.pid)"
        rm -f /var/run/my_process.pid
        ./manage_my_process &
        touch /var/run/my_process.pid
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process restarted"
    else
	    echo "Usage: manage_my_process {start|stop|restart}"
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi