#!/usr/bin/env bash
# This is a script that displays the content of the file /etc/passwd and:
# - displays only the username
# - displays only the assigned user ID
# - displays path to the home directory to the user

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
    echo "$f1:$f3:$f6"
done < /etc/passwd