#!/usr/bin/env bash
# This is a script that displays the content of the file /etc/passwd and:
# - displays only the username
# - displays only the assigned user ID
# - displays path to the home directory to the user
# - displays the default shell of the user
# - displays the user's home directory
# - displays the user's groups separated by commas


while IFS=':' read -r f1 f2 f3 f4 f5 f6 f7
do
    echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
done < /etc/passwd