#!/usr/bin/env bash
# This is a script that parses web servers in TSV format as input and displays the 11 hosts or IP addresses which did the most requests


awk '{print $1, $9}' ./apache-access.log | sort | uniq -c | sort -nr 