#!/usr/bin/env bash
# This is a script that prints 10 times "Best School" but the 9th is Hi

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$((i+1))
done