#!/usr/bin/env bash
# This is a script that prints 10 times "Best School" but for the 9th iteration, displays Best School and then Hi on a new line.

for (( i=1; i<=10; i++ ))
do
    if [ $i -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
done