#!/usr/bin/env bash
# This is a script that prints 10 times "Best School" but the 4th time, it prints "bad luck", the 8th time "good luck"

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i+1))
done