#!/usr/bin/env bash
# This is a script that prints numbers from 1 to 20 and:
# - the 4th bad luck from China
# - the 9th bad luck from Japan
# - the 17th bad luck from Italy

i=1

while [ $i -le 20 ]
do
    case $i in
        4)
            echo "$i"$'\n'"bad luck from China"
            ;;
        9)
            echo "$i"$'\n'"bad luck from Japan"
            ;;
        17)
            echo "$i"$'\n'"bad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac
    i=$((i+1))
done