#!/usr/bin/env bash
# This is a script that checks if a file exists and: if it exists, if it is empty, and if it is a regular file (print custom messages for each case)

if [ -e /tmp/school ]
then
    echo "school file exists"
    if [ -s /tmp/school ]
    then
        echo "school file is not empty"
        if [ -f /tmp/school ]
        then
            echo "school is a regular file"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi